### ISSUE TITLE
Gracefully handle HOME access failure?

### ISSUE THREAD

**Issue by brycefisher** [js-cli/js-v8flags#19]
Related to shipitjs/shipit#70 and tkellen/js-v8flags#13 , if HOME is not accessible, this can cause upstream modules that require liftoff to fail (even if they don't explicitly need any specific v8flags).

Is it possible to issue a warning and keep going if v8flags fails for some reason? The specific case I ran into today is where the uid executing the node process doesn't have access to the $HOME directory.

**Comment by tkellen** [comment]
Thanks @brycefisher! This module has gone through a tremendous amount of churn to cover all the possible edge cases of writing a silly configuration file. Yours is the first failure in some time. Rather than have v8flags return an empty array of options in a failure case (or have Liftoff ignore v8flags bailing), I'd like to fix the underlying cause.

Could you confirm for me if the uid has access to the temp directory that results from running this? If it does, I think I know what needs to be done.
```
function tempdir() {
  if (process.platform === 'win32') {
    return process.env.TEMP ||
           process.env.TMP ||
           (process.env.SystemRoot || process.env.windir) + '\\temp';
  } else {
    return process.env.TMPDIR ||
           process.env.TMP ||
           process.env.TEMP ||
           '/tmp';
  }
};
```

**Comment by tkellen** [comment]
PS: this is from the `os` module, so you can also do `require('os').tmpdir()`

**Comment by brycefisher** [comment]
Yes! We've resolved that issue by modify the environment, but I'll try to recreate via a docker image tonight. Thanks!

**Comment by tkellen** [comment]
Sounds good! The current scenario where a temporary directory is used rather than a home directory is when no home directory can be found. I believe we can resolve this by instead checking for write access to the home dir. This will fail in the current case (if no home directory is found, if course you can't write to it) and your case, (having a home directory but not being able to write to it). Obviously the failover only works if you can actually write to the tmpdir, though.

Honestly, it seems a bit nonsensical that you actually have a value for the home directory but you can't write to it? How is that happening?

**Comment by brycefisher** [comment]
Yeah it was a little weird. We had an ec2 instance running jenkins. Jenkins had a separate user, but apparently no one had configured the home directory properly. I was a little sad that having the home directory setup properly would cause a shipit dependency to fail, but it is a bit of edge case.

**Comment by brycefisher** [comment]
Despite my best efforts at this, I'm unable to reproduce the issue we ran into in my docker image:
https://github.com/brycefisher/js-v8flags-no-home-dir

Running `require('os').tmpdir()` inside that image gave `/tmp` and unsurprising the `unpriv` user can access temp. Sooooo I'm thinking maybe that user didn't have access to /tmp as well... I'll investigate further from the office tomorrow.

**Comment by tkellen** [comment]
Thanks for investigating @brycefisher. Standing by for more.

**Comment by brycefisher** [comment]
Okay, I did a little more digging and it looks like the tmpdir is fine:

![screen shot 2015-05-28 at 10 22 55 am](https://cloud.githubusercontent.com/assets/220106/7866949/b39edc36-0527-11e5-9574-741d6441201b.png)

![screen shot 2015-05-28 at 10 14 32 am](https://cloud.githubusercontent.com/assets/220106/7866952/b59aba96-0527-11e5-981e-3cbccd7f1f02.png)

However, the failures happened when the `$HOME` directory pointed at a non-existent directory.  I'm trying to test that situation now to see if I can reproduce the issues we had.

**Comment by brycefisher** [comment]
Hmm tried to reproduce the situation locally, and I still wasn't able to exactly reproduce this issue:

index.js
```
var v8flags = require('v8flags');

v8flags(function (err, results) {
  console.log(results);  // [ '--use_strict',
                         //   '--es5_readonly',
                         //   '--es52_globals',
                         //   '--harmony_typeof',
                         //   '--harmony_scoping',
                         //   '--harmony_modules',
                         //   '--harmony_proxies',
                         //   '--harmony_collections',
                         //   '--harmony',
                         // ...
});
```

bash:
```
$ ls -lah /usr/lib/no-exist
ls: /usr/lib/no-exist: No such file or directory
$ HOME=/usr/lib/no-exist node index.js
undefined
```

**Comment by tkellen** [comment]
> However, the failures happened when the $HOME directory pointed at a non-existent directory. I'm trying to test that situation now to see if I can reproduce the issues we had.

That's what I suspected was the problem, and we can definitely fix that. It's not enough to detect if a home path can be found in the environment, we also have to ensure you can write to it, which is something v8flags currently takes for granted.

**Comment by brycefisher** [comment]
Yay! I was getting hopeless about reproducing this.

**Comment by brycefisher** [comment]
Is there a big impact on performance to check for write access?

**Comment by tkellen** [comment]
Nah, it should be fine.

**Comment by ilikebits** [comment]
@brycefisher, I just pushed 2.0.11 which should resolve this issue. Can you see if this fix works for you?

**Comment by brycefisher** [comment]
Woot! Sadly, I've left that project and blew away my whole setup. Thanks so much for fixing this!!

**Comment by ilikebits** [comment]
Sure thing. Looks like this seems to be working for people from #22, so I'm going to go ahead and close this issue now.
