### ISSUE TITLE
Save cached config to standard directories

### ISSUE THREAD

**Issue by Siilwyn** [js-cli/js-v8flags#37]
Instead of placing the configuration file in the home directory it should be placed in the [appropriate directory](https://wiki.archlinux.org/index.php/XDG_Base_Directory_support) per OS. This introduces a breaking change unless some fallback or migration logic is added. I'd rather not do that because it results in extra code that should be removed in the future.

See this original but [reverted PR](https://github.com/js-cli/js-v8flags/pull/21) for context. Thought I would open an issue to give it a place to track and possibly discuss.

**Comment by tkellen** [comment]
:+1: looking forward to seeing your implementation!
